# Generated by Django 5.2.4 on 2025-07-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_instruction_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.customuser'),
        ),
    ]
